# Generated by Django 3.1.7 on 2021-03-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=50)),
                ('chinese_sentences', models.CharField(max_length=250)),
                ('enlish_sentences', models.CharField(max_length=250)),
                ('speech', models.CharField(choices=[('n', 'n.'), ('pron', 'pron.'), ('v', 'v.'), ('adj', 'adj.'), ('adv', 'adv.'), ('prep', 'prep.'), ('conj', 'conj.'), ('int', 'int.')], max_length=4)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.characterset'),
        ),
    ]
