# Generated by Django 3.1.7 on 2021-06-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20210511_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='speech',
            field=models.CharField(choices=[('n', 'n.'), ('pron', 'pron.'), ('v', 'v.'), ('adj', 'adj.'), ('adv', 'adv.'), ('prep', 'prep.'), ('conj', 'conj.'), ('int', 'int.'), ('aux', 'aux.')], max_length=5),
        ),
    ]
