# Generated by Django 3.1.7 on 2021-06-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_characterset_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField()),
                ('total', models.IntegerField()),
                ('character_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.characterset')),
            ],
        ),
    ]
