# Generated by Django 3.1.7 on 2021-06-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='examMethod',
            field=models.CharField(choices=[('1', '中翻英'), ('2', '英翻中'), ('3', '克漏字')], default=None, max_length=1),
        ),
    ]
