# Generated by Django 3.1.7 on 2021-06-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_score_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='examMethod',
            field=models.CharField(choices=[('中翻英', '1'), ('英翻中', '2'), ('克漏字', '3')], default=None, max_length=3),
        ),
    ]
