# Generated by Django 3.1.7 on 2021-06-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_auto_20210627_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='examMethod',
            field=models.CharField(choices=[('0', '中翻英'), ('1', '英翻中'), ('2', '克漏字')], default=None, max_length=1),
        ),
    ]
