# Generated by Django 3.1.7 on 2021-02-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_text', models.CharField(max_length=50)),
                ('words_chinese', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentences', models.CharField(max_length=200)),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.words')),
            ],
        ),
    ]
