# Generated by Django 3.1.7 on 2021-02-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentences',
            old_name='sentences',
            new_name='sentences_text',
        ),
    ]
