# Generated by Django 3.1.7 on 2021-02-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_auto_20210221_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sentences',
            new_name='Sentence',
        ),
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='sentences_text',
            new_name='sentence_text',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='words',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='words_chinese',
            new_name='word_chinese',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='words_text',
            new_name='word_text',
        ),
    ]
